server:
  port: 8200

spring:
  profiles:
    active: dev

springdoc:
  packagesToScan: com.example.sdui
  swagger-ui:
    path: /api-docs
    groups:
      enabled: false

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
