server:
  servlet:
    context-path: /sdui
  port: 8200

# AJP
tomcat:
  ajp:
    protocol: AJP/1.3
    port: 8201
    enable: true
    scheme: http

spring:
  profiles:
    active: dev

springdoc:
  packagesToScan: com.example.sdui
  swagger-ui:
    path: /api-docs
    groups:
      enabled: false

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
