spring:
  h2:
    console:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
    hibernate:
      ddl-auto: none


