package com.example.sdui.support;

import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

import org.hibernate.Session;
import org.hibernate.engine.spi.SessionFactoryImplementor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import jakarta.annotation.PostConstruct;
import jakarta.persistence.EntityManager;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.Table;
import jakarta.persistence.metamodel.EntityType;

@Component
public class DatabaseCleanUp {

	@PersistenceContext
	private EntityManager entityManager;

	private List<TableTuple> tableTuples;

	private final DatabaseStrategy databaseStrategy;

	@Autowired
	public DatabaseCleanUp(EntityManager entityManager, Map<String, DatabaseStrategy> strategies) {
		this.entityManager = entityManager;
		this.databaseStrategy = determineDatabaseStrategy(strategies);
	}

	private DatabaseStrategy determineDatabaseStrategy(Map<String, DatabaseStrategy> strategies) {
		Session session = entityManager.unwrap(Session.class);
		SessionFactoryImplementor sessionFactory = (SessionFactoryImplementor)session.getSessionFactory();
		String dialectName = sessionFactory.getJdbcServices().getDialect().getClass().getSimpleName();

		return Optional.ofNullable(strategies.get(dialectName))
			.orElseThrow(() -> new UnsupportedOperationException("Unsupported database: " + dialectName));
	}

	@PostConstruct
	public void init() {
		this.tableTuples = entityManager.getMetamodel().getEntities().stream()
			.map(EntityType::getJavaType)
			.map(TableTuple::of)
			.filter(TableTuple::isAutoGeneratedId)
			.collect(Collectors.toList());
	}

	@Transactional
	public void execute() {
		entityManager.flush();

		databaseStrategy.disableConstraints(entityManager);

		for (TableTuple tuple : tableTuples) {
			entityManager.createNativeQuery(databaseStrategy.getTruncateTableQuery(tuple.name)).executeUpdate();
			entityManager.createNativeQuery(databaseStrategy.getResetAutoIncrementQuery(tuple.name, tuple.id))
				.executeUpdate();
		}

		databaseStrategy.enableConstraints(entityManager);
	}

	private static class TableTuple {
		public String name;
		public String id;

		public TableTuple(final String name, final String id) {
			this.name = name;
			this.id = id;
		}

		public static TableTuple of(Class<?> entityType) {
			return new TableTuple(tableName(entityType), id(entityType));
		}

		private static String tableName(final Class<?> entityType) {
			return entityType.getAnnotation(Table.class).name();
		}

		private static String id(final Class<?> entityType) {
			return Arrays.stream(entityType.getDeclaredFields())
				.filter(field -> field.getAnnotation(Id.class) != null)
				.filter(field -> field.getAnnotation(GeneratedValue.class) != null)
				.map(Field::getName)
				.findAny()
				.orElse("");
		}

		public static boolean isAutoGeneratedId(TableTuple tableTuple) {
			return !tableTuple.id.equals("");
		}
	}
}
